db:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "Bossza555"
  table: "user"

db2:
  driver: "mysql"
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "Bossza555"
  database: user