version: '1'

services:
  db:
    image: postgres:14beta2-alpine3.14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: user
    ports:
      - "5432:5432"